### ISSUE TITLE
♻️ API 리팩토링

### ISSUE THREAD

**Issue by fromitive** [team-sonamu/backend-chongdae-market#14]
## 📌 Description
- API 리펙토링 코멘트 반영

## 📝 To-do

- 참여하기
  - [x] ArticleErrorCode lombok 적용
  - [x] request NotNull 검증 어노테이션 추가
- 공동구매 목록 조회
  - [x] 엔빵계산을 공동구매 게시글 도메인에 추가
  - [x] splitPrice를 dividedPrice 로 변경
  - [x] 게시글이 없을 경우 예외 처리

## 예상 소요 시간
- 0.5h
- `1h`
- 1.5h
- 2h
- 2.5h
- 3h+
