### ISSUE TITLE
✨ 참여하기 API 구현

### ISSUE THREAD

**Issue by fromitive** [team-sonamu/backend-chongdae-market#8]
## 📌 Description
- 공동구매를 참여할 수 있는 기능 구현

## 📝 To-do
- [x] 참여하기 API 구현
- [x] 참여하기 예외처리 구현
- [x] 참여하기가 성공할 때 게시물의 현재 인원수를 증가

## 예상 소요 시간
- 0.5h
- 1h
- 1.5h
- `2h`
- 2.5h
- 3h+
